### ISSUE TITLE
Error in PySceneDetect

### ISSUE THREAD

**Issue by Manlycookiebear** [natis1/qencoder#14]
First of all, great program, thanks a lot for it!

I did try to convert some .flv (H264) files and as soon as I start the encode, it stops and the log file only has one entry:

**Error in PySceneDetect: OpenCV VideoCapture object failed to return True when calling isOpened().**

What can be done about this?

**Comment by natis1** [comment]
I am able to reproduce this error. It's driving me a little crazy since I don't know why it's breaking but I will look into it

**Comment by natis1** [comment]
Hi, just to make sure we are on the same page though and having the same problem, do you have any samples you could send that you tested that resulted in this error? I am following pyscenedetect's default setup.

**Comment by Manlycookiebear** [comment]
Thanks for looking into that issue! 

Yes, I can provide you with a file that results in this error. Is a Firefox Send link ok?

[https://send.firefox.com/download/f86a450c04649041/#uRlsl9XNuXx9ehxUbQ4axA](url)

**Comment by natis1** [comment]
Hey, I am not able to reproduce this with the video you sent me. Are you on Windows? If so maybe it might be an issue with the ffmpeg version that is distributed. I will investigate further.

**Comment by Manlycookiebear** [comment]
Yes, I'm on Windows 10.

**Comment by master-of-zen** [comment]
@Manlycookiebear @natis1 OpenCV VideoCapture object failed to return True when calling isOpened(). Is an error that appears when openCV can't properly read video stream, usually it's means 2 things, OpenCV can't open codec that is used, or there is multiple video streams, for example one for video and second is a thumbnail for file and OpenCV try to open second one and returns error.
For checking is that true try transcode couple of seconds of your source to lossless h264, and try it.

**Comment by natis1** [comment]
I can confirm that the source should work as I tested it and it works on my system but the version of ffmpeg shipped with windows may be unable to handle it, it may be possible to workaround by swapping the ffmpeg binary for a newer or more complete one though.

**Comment by Manlycookiebear** [comment]
I have tried using a newer ffmpeg version, but that either didn't work or it did not resolve the error. 

But I have also tried to reencode like @master-of-zen mentioned and that did work. No more PySceneDetect error and the encode works beautifully.

**Comment by natis1** [comment]
Unfortunately, there is no version of ffmpeg I am allowed to distribute that is capable of decoding flv files. If you need this feature there is nothing now I can do. In the newest release (1.1.1) if splitting fails it will continue as normal but only use one job.

**Comment by natis1** [comment]
With this said. there are a few workarounds I am looking into. But nothing that will directly fix this issue.
