### ISSUE TITLE
Audio not getting passed through/transcoded on qencoder 1.3 (Windows build)

### ISSUE THREAD

**Issue by jay-ramani** [natis1/qencoder#16]
I tried converting a 1.2GB video (parameters in detail below) to AV1, only to find that the encoded file (12MB in size) does not have any audio stream. I tried with both audio pass-through and conversion to Opus as well.

version: qencoder 1.3
Source video parameters:
```
Video: MPEG4 1920x1080 30.001fps [V: h264 L4.1, yuv420p]
Audio: AAC [A: aac lc, 48000 Hz, stereo]
```
Encoded video parameters:
`Video: AV01 1920x1080 30.001fps [V: av1, yuv420p10le]`

Encoding settings used from the qencoder GUI:

- Two-pass
- Reencode audio (tried with and without being enabled)
- Quality preset: Amazing (crf20)
- Speed preset: Medium
- 10-bit output enabled

All other qencoder parameters are defaults.

Hope I'm not doing anything wrong. Would be great if you can test the build and confirm.

Let me know how I can help in resolving the issue.

**Comment by natis1** [comment]
Uh oh. That's a big problem if so. I will look into this asap and get back to you in a few days.

**Comment by natis1** [comment]
I don't believe I am allowed to distribute a version of ffmpeg that can decode aac and I cannot replicate this with any other audio codecs. Use a different audio format or swap the ffmpeg binaries out.

**Comment by jay-ramani** [comment]
Should not the pass-through at least work? Did you try it? I'm able to consistently reproduce with and without pass-through.

Thanks.

**Comment by natis1** [comment]
Hey jay, if it doesn't its an issue with ffmpeg that I cannot fix on my end. Try swapping out the ffmpeg binaries for one that includes non-free codecs.

**Comment by jay-ramani** [comment]
Thanks for the confirmation Eli. Will try using an alternate ffmpeg, and update here as well in case others run into the issue.

Cheers,
Jay
