### ISSUE TITLE
Core dumped after initial scene splitting

### ISSUE THREAD

**Issue by Qwertie-** [natis1/qencoder#19]
Using the latest version available from pip (qencoder 1.0 iirc) on fedora 32 whenever the first loading bar finishes the program will crash with this output

```
Queue: 1 Workers: 1 Passes: 2
Params: --threads=4 --tile-columns=2 --tile-rows=1 --cpu-used=3 --good --end-usage=q --cq-level=24 --bit-depth=8  --i420
Error in encoding loop invalid literal for int() with base 10: 'oska,webm @ 0x5601ffc0fc40] Duplicate element\n[matroska,webm @ 0x5601ffc0fc40] 0x00 at pos 178 (0xb2) invalid as first byte of an EBML number\n[matroska,webm @ 0x5601ffc0fc40] Duplicate element\n[ma
At line 451
Concatenation failed, FFmpeg error
Segmentation fault (core dumped)

```

I have noticed this only happens with a few videos which are mpeg-4 in an AVI container. On mp4 files it seems to work fine. A different but still fatal error was logged with the AVI videos on Av1an as well.

**Comment by natis1** [comment]
This miiight be related to your ffmpeg version. I will investigate.

**Comment by natis1** [comment]
This may be fixed by the latest version, please test.
