### ISSUE TITLE
Bulk file selection

### ISSUE THREAD

**Issue by Qwertie-** [natis1/qencoder#20]
The queue feature would be much quicker to use if it was possible to select an entire folder as the input and a folder for the output and the output filename is just the original filename with the correct extension.

**Comment by natis1** [comment]
This will be added to 1.5 as a menu option, which will add every video in a folder to the queue. Because this behavior is not that intuitive, I don't see myself able to add it anywhere else, and it will probably also need a dedicated popup for it.

**Comment by natis1** [comment]
Added to 2.0. if you git pull the current master it will have it.
