### ISSUE TITLE
Output fails on windows

### ISSUE THREAD

**Issue by ghost** [natis1/qencoder#21]
Using the latest version (1.5) output will fail if there are spaces in the path or filename.
So, if the path is _C:\Some Folder_, or filename is _Video File.mp4_, qencoder will fail to output anything. It will still encode the file, and it is possible to manually join the encoded parts, but it will not concat the resulting files. If there are no spaces in path or filename, it will encode fine.
This issue was not present in the previous version (1.3) which did not have problems with spaces in path or filename.

**Comment by natis1** [comment]
Thanks for letting me know. I will look into this. Spaces in filenames seem to break on Linux as well.

**Comment by natis1** [comment]
Fixed in 1.5.4
