### ISSUE TITLE
[Question] How to save in .webm extension

### ISSUE THREAD

**Issue by Tox86** [natis1/qencoder#24]
Hello, so that is may question
cheers.

**Comment by natis1** [comment]
If you click save to... and specify an extension of .webm it will not replace it with .mkv.

**Comment by natis1** [comment]
https://cdn.discordapp.com/attachments/709456507737211008/741410643114065970/amazing-2020-08-07_15.40.43.webm

Here's a video to demonstrate the process

**Comment by Tox86** [comment]
Suggestion. It is possible save with the same file name in the output path.

**Comment by natis1** [comment]
It's possible but not recommended. It will overwrite your original video which you may want to keep around just in case.
