### ISSUE TITLE
About cropping and target vmaf

### ISSUE THREAD

**Issue by lastrosade** [natis1/qencoder#26]
VMAF can not work on videos with a different aspect resolution, target VMAF should be hard disabled if cropping is enabled.

You could fix this by first trans-coding the video to a lossless codec.

**Comment by master-of-zen** [comment]
There is option `--vmaf_filter` which allows to pass filter to vmaf calculation

**Comment by lastrosade** [comment]
Ok then, pass the crop filter to --vmaf_filter too if target vmaf is enabled then.

**Comment by natis1** [comment]
Yeah. this seems like the most reasonable approach and what I am testing right now
