### ISSUE TITLE
Qencoder finds not aomenc

### ISSUE THREAD

**Issue by correveidile** [natis1/qencoder#5]
First, excuse if what I say is too elemental, I am only an user witouth knowleges of programming. I have opened this account only to report this bug. Sorry for my inexperience and for my bad english.

I have instaled Qencoder and is Cool. I'm so tired of GTK apps... I like that the graphic interface follows the KDE lema "simple by default, powerful when needed", altought I would add preview and time selection, like Boram (https://github.com/Kagami/boram).
The problem is that it seems like Qencoder can not find Aomenc but I have it, libaom-1.0.0_p20200507, to be precise; but neverless, once I clic «Encode» and the first part of the proces (when the program splits the file original) endes, I get this error:

> Error in encoding loop invalid literal for int() with base 10: '/media/ramdisk/qencoder/temp/encode/0010.ivf: No such file or directory'
> At line 415
> Encoding error: unsupported operand type(s) for +=: 'int' and 'NoneType'
> At line 503

I have looked the file log.log and there are a lot of messages like:

> ffmpeg -y -hide_banner [...] --fpf=/media/ramdisk/qencoder/temp/split/0004.log -o /dev/null - /bin/sh: aomenc: orden no encontrada
> /bin/sh: aomenc: orden no encontrada
> av_interleaved_write_frame(): Broken pipe
> Error writing trailer of pipe:: Broken pipe

«Orden no encontrada» means «Command not found», but as I said before, aomenc is present in my PC, in fact, I can encode to AV1 using pure FFMPEG (obviously at an unsuportable speed, but it works perfectly). So, I think that for some reason Qencode can not find aomenc.
I have the latest version of Qencoder cloned from this repository.

**Comment by natis1** [comment]
Hey, is aomenc on your path? can it be called with the command: `aomenc`? Feel free to reopen this if so.
